version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  node: circleci/node@5
executors:
  aws-executor:
    docker:
      - image: "cimg/node:22.5.1"
jobs:
  build:
    executor: aws-executor
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - checkout
      - run:
          name: "Install AWS CDK Locally"
          command: |
            npm install aws-cdk
            export PATH=$PATH:$(npm bin)
      - run:
          name: "Build CDK App"
          command: |
            npm install
            npm run build
      - run:
          name: "Test Cases"
          command: |
            npm test
      - run:
          name: "cdk_deploy"
          command: |
            cdk deploy --require-approval never
workflow:
  cdk-deployment:
    jobs:
      - build
